-- stage 1
-- This query combines data retrieval from FIRMS, CUSTS,  AGNTS , ENTITIES , ACNTS , ACNTS_DTLS tables
SELECT 
    "FIRMS"."FIRM_LONG_NAME",
    "FIRMS"."FIRM_CODE",
    "ACNTS"."ACNT_CODE",
    "CUSTS"."CUST_CODE",
    "CUSTS"."AGNT_CODE",
    "AGNTS"."CUST_LONG_DSCR" AS "AGNT_CUST_LONG_DSCR",
    "CUSTS"."CUST_LONG_DSCR",
    "CUSTS"."ENT_CODE",
    "CUSTS"."CRE_DATE",
    "CUSTS"."ACTV_Y_N",
    "CUSTS"."MAX_CREDIT",
    "CUSTS"."RLBL",
    "ENTITIES"."ENT_LONG_NAME",
    "ACNTS_DTLS"."PMNT_TYPE",
    "DOR_CUSTS"."CLOSE_RSN", 
    "DOR_CUSTS"."CLOSE_DATE"
FROM 
    "DBTRANS"."FIRMS" "FIRMS"
    JOIN "DBTRANS"."CUSTS" "CUSTS"
        ON "FIRMS"."FIRM_CODE" = "CUSTS"."FIRM_CODE"
    LEFT JOIN "DBTRANS"."CUSTS" "AGNTS"
        ON "CUSTS"."FIRM_CODE" = "AGNTS"."FIRM_CODE"
        AND "CUSTS"."AGNT_CODE" = "AGNTS"."CUST_CODE"
    LEFT JOIN "DBTRANS"."ENTITIES" "ENTITIES"
        ON "CUSTS"."ENT_CODE" = "ENTITIES"."ENT_CODE"
        
    LEFT OUTER JOIN "DBTRANS"."ACNTS" "ACNTS"
        ON "CUSTS"."ACNT_CODE" = "ACNTS"."ACNT_CODE"
        AND "CUSTS"."FIRM_CODE" = "ACNTS"."FIRM_CODE"
 LEFT OUTER JOIN "DBTRANS"."ACNTS_DTLS" "ACNTS_DTLS"
        ON "ACNTS"."FIRM_CODE" = "ACNTS_DTLS"."FIRM_CODE"
        AND "ACNTS"."ACNT_CODE" = "ACNTS_DTLS"."ACNT_CODE"
          INNER JOIN "DBTRANS"."DOR_CUSTS" "DOR_CUSTS"
        ON "CUSTS"."FIRM_CODE" = "DOR_CUSTS"."FIRM_CODE"
        AND "CUSTS"."CUST_CODE" = "DOR_CUSTS"."CUST_CODE"
WHERE 
   "FIRMS"."FIRM_CODE" = 21 -- External parameter for filtering by firm_code
    AND "CUSTS"."CUST_CODE" = '1' -- External parameter for filtering by cust_code
 -- "ACNTS"."ACNT_CODE" = 100
ORDER BY 
    "CUSTS"."AGNT_CODE", 
    "CUSTS"."CUST_LONG_DSCR";
-- ====================================================================




-- Stage 2: Retrieve Logistic Document Details
-- This stage retrieves data from the LGSTC_ACTL_DOCS table, which depends on firm_code and cust_code
SELECT 
    "LGSTC_ACTL_DOCS"."DOC_NBR",
    "LGSTC_ACTL_DOCS"."EVNT_DATE",
    "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS",
    "LGSTC_ACTL_DOCS"."TRNS_STAT",
    "LGSTC_ACTL_DOCS"."FREE_FLD_1"
FROM 
    "DBTRANS"."LGSTC_ACTL_DOCS" "LGSTC_ACTL_DOCS"
WHERE 
    "LGSTC_ACTL_DOCS"."FIRM_CODE" = 21 -- External parameter for filtering by firm_code
    AND "LGSTC_ACTL_DOCS"."CUST_CODE" = '1' -- External parameter for filtering by cust_code
    AND ("LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" = 323 OR "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" = 325)
    AND ("LGSTC_ACTL_DOCS"."TRNS_STAT" >= 20 AND "LGSTC_ACTL_DOCS"."TRNS_STAT" <= 40)
    AND "LGSTC_ACTL_DOCS"."EVNT_DATE" >= TO_DATE('01-01-2007 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
    AND ("LGSTC_ACTL_DOCS"."FREE_FLD_1" = '1' OR "LGSTC_ACTL_DOCS"."FREE_FLD_1" = '2');

-- ====================================================================
-- Stage 3: Retrieve Logistic Transaction and Part Details
-- This stage retrieves data from the LGSTC_ACTL_TRNS and PARTS tables, which depend on logistic documents and transactions
SELECT 
    -- Fields from LGSTC_ACTL_TRNS table
    "LGSTC_ACTL_TRNS"."LINE_TRNS_STAT",
    "LGSTC_ACTL_TRNS"."LINE_SIGN",
    "LGSTC_ACTL_TRNS"."QNTY_1",
    "LGSTC_ACTL_TRNS"."PART_CODE",
    "LGSTC_ACTL_TRNS"."PRMY_TRNS_CLSS",
    "LGSTC_ACTL_TRNS"."DOC_NBR",
    -- Fields from PARTS table
    "PARTS"."PART_CODE",
    "PARTS"."PART_SHRT_NAME",
    "PARTS"."PART_LONG_NAME"
FROM 
    "DBTRANS"."LGSTC_ACTL_TRNS" "LGSTC_ACTL_TRNS"
    INNER JOIN "DBTRANS"."PARTS" "PARTS"
        ON "LGSTC_ACTL_TRNS"."FIRM_CODE" = "PARTS"."FIRM_CODE"
        AND "LGSTC_ACTL_TRNS"."PART_CODE" = "PARTS"."PART_CODE"
    left join "DBTRANS"."LGSTC_ACTL_DOCS" "LGSTC_ACTL_DOCS"
        ON "LGSTC_ACTL_TRNS"."FIRM_CODE" = "LGSTC_ACTL_DOCS"."FIRM_CODE"
        AND "LGSTC_ACTL_TRNS"."PRMY_TRNS_CLSS" = "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS"
        AND "LGSTC_ACTL_TRNS"."DOC_NBR" = "LGSTC_ACTL_DOCS"."DOC_NBR"
WHERE 
    "LGSTC_ACTL_TRNS"."FIRM_CODE" = 21 -- External parameter for filtering by firm_code
    AND ("LGSTC_ACTL_TRNS"."LINE_TRNS_STAT" >= 20 AND "LGSTC_ACTL_TRNS"."LINE_TRNS_STAT" <= 40)
    AND "LGSTC_ACTL_DOCS"."CUST_CODE" = '1' -- External parameter for filtering by cust_code
    AND ("LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" = 323 OR "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" = 325)
    AND ("LGSTC_ACTL_DOCS"."TRNS_STAT" >= 20 AND "LGSTC_ACTL_DOCS"."TRNS_STAT" <= 40)
    AND "LGSTC_ACTL_DOCS"."EVNT_DATE" >= TO_DATE('01-01-2007 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
    AND ("LGSTC_ACTL_DOCS"."FREE_FLD_1" = '1' OR "LGSTC_ACTL_DOCS"."FREE_FLD_1" = '2');



-- Original Query: Fields Ordered by Stages
-- This query retrieves data from multiple tables with fields grouped by their respective stages
SELECT 
    -- Stage 1: Fields from FIRMS, CUSTS, AGNTS, and ENTITIES tables
    "FIRMS"."FIRM_LONG_NAME", 
    "FIRMS"."FIRM_CODE", 
    "CUSTS"."AGNT_CODE", 
    "AGNTS"."CUST_LONG_DSCR" AS "AGNT_CUST_LONG_DSCR", 
    "CUSTS"."CUST_CODE", 
    "CUSTS"."CUST_LONG_DSCR", 
    "CUSTS"."ENT_CODE", 
    "CUSTS"."CRE_DATE", 
    "CUSTS"."ACTV_Y_N", 
    "CUSTS"."MAX_CREDIT", 
    "CUSTS"."RLBL", 
    "ENTITIES"."ENT_LONG_NAME",
    "ACNTS"."FIRM_CODE" AS "ACNTS_FIRM_CODE", 
    "ACNTS"."ACNT_CODE", 
    "ACNTS_DTLS"."PMNT_TYPE",
    "DOR_CUSTS"."CLOSE_RSN", 
    "DOR_CUSTS"."CLOSE_DATE",
    -- Stage 2: Fields from LGSTC_ACTL_DOCS table
    "LGSTC_ACTL_DOCS"."EVNT_DATE", 
    "LGSTC_ACTL_DOCS"."CUST_CODE", 
    "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS", 
    "LGSTC_ACTL_DOCS"."TRNS_STAT", 
    "LGSTC_ACTL_DOCS"."FREE_FLD_1", 
    "LGSTC_ACTL_DOCS"."FIRM_CODE" AS "DOC_FIRM_CODE",
    -- Stage 3: Fields from LGSTC_ACTL_TRNS and PARTS tables
    "LGSTC_ACTL_TRNS"."LINE_TRNS_STAT", 
    "LGSTC_ACTL_TRNS"."LINE_SIGN", 
    "LGSTC_ACTL_TRNS"."QNTY_1", 
    "LGSTC_ACTL_TRNS"."PART_CODE", 
    "PARTS"."PART_CODE", 
    "PARTS"."PART_SHRT_NAME", 
    "PARTS"."PART_LONG_NAME"
FROM 
    "DBTRANS"."LGSTC_ACTL_DOCS" "LGSTC_ACTL_DOCS"

    INNER JOIN "DBTRANS"."LGSTC_ACTL_TRNS" "LGSTC_ACTL_TRNS"
        ON "LGSTC_ACTL_DOCS"."FIRM_CODE" = "LGSTC_ACTL_TRNS"."FIRM_CODE"
        AND "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" = "LGSTC_ACTL_TRNS"."PRMY_TRNS_CLSS"
        AND "LGSTC_ACTL_DOCS"."DOC_NBR" = "LGSTC_ACTL_TRNS"."DOC_NBR"

    INNER JOIN "DBTRANS"."PARTS" "PARTS"
        ON "LGSTC_ACTL_TRNS"."FIRM_CODE" = "PARTS"."FIRM_CODE"
        AND "LGSTC_ACTL_TRNS"."PART_CODE" = "PARTS"."PART_CODE"


    INNER JOIN "DBTRANS"."CUSTS" "CUSTS"
        ON "LGSTC_ACTL_DOCS"."FIRM_CODE" = "CUSTS"."FIRM_CODE"
        AND "LGSTC_ACTL_DOCS"."CUST_CODE" = "CUSTS"."CUST_CODE"

    INNER JOIN "DBTRANS"."FIRMS" "FIRMS"
        ON "LGSTC_ACTL_DOCS"."FIRM_CODE" = "FIRMS"."FIRM_CODE"

    LEFT OUTER JOIN "DBTRANS"."CUSTS" "AGNTS"
        ON "CUSTS"."FIRM_CODE" = "AGNTS"."FIRM_CODE"
        AND "CUSTS"."AGNT_CODE" = "AGNTS"."CUST_CODE"

    INNER JOIN "DBTRANS"."DOR_CUSTS" "DOR_CUSTS"
        ON "CUSTS"."FIRM_CODE" = "DOR_CUSTS"."FIRM_CODE"
        AND "CUSTS"."CUST_CODE" = "DOR_CUSTS"."CUST_CODE"

    LEFT OUTER JOIN "DBTRANS"."ENTITIES" "ENTITIES"
        ON "CUSTS"."ENT_CODE" = "ENTITIES"."ENT_CODE"

    LEFT OUTER JOIN "DBTRANS"."ACNTS" "ACNTS"
        ON "CUSTS"."ACNT_CODE" = "ACNTS"."ACNT_CODE"
        AND "CUSTS"."FIRM_CODE" = "ACNTS"."FIRM_CODE"

    LEFT OUTER JOIN "DBTRANS"."ACNTS_DTLS" "ACNTS_DTLS"
        ON "ACNTS"."FIRM_CODE" = "ACNTS_DTLS"."FIRM_CODE"
        AND "ACNTS"."ACNT_CODE" = "ACNTS_DTLS"."ACNT_CODE"
        

WHERE 
    ("LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" = 323 OR "LGSTC_ACTL_DOCS"."PRMY_TRNS_CLSS" = 325)
    AND ("LGSTC_ACTL_DOCS"."TRNS_STAT" >= 20 AND "LGSTC_ACTL_DOCS"."TRNS_STAT" <= 40)
    AND ("LGSTC_ACTL_TRNS"."LINE_TRNS_STAT" >= 20 AND "LGSTC_ACTL_TRNS"."LINE_TRNS_STAT" <= 40)
    AND "LGSTC_ACTL_DOCS"."EVNT_DATE" >= TO_DATE('01-01-2007 00:00:00', 'DD-MM-YYYY HH24:MI:SS')
    AND ("LGSTC_ACTL_DOCS"."FREE_FLD_1" = '1' OR "LGSTC_ACTL_DOCS"."FREE_FLD_1" = '2')
ORDER BY 
    "CUSTS"."AGNT_CODE", 
    "CUSTS"."CUST_LONG_DSCR";



-- pmnt_acnt_trns
select 
"PRMNT_ACNTNG_TRNS"."LINE_SIGN",
"PRMNT_ACNTNG_TRNS"."PRMY_TRNS_CLSS",
acnts.acnt_code,
PRMNT_ACNTNG_TRNS.CONTRA_ACNT,
PRMNT_ACNTNG_TRNS.FIRM_CODE,
PRMNT_ACNTNG_TRNS.DOC_NBR,
PRMNT_ACNTNG_TRNS.BLNC_YEAR,
PRMNT_ACNTNG_TRNS.EVNT_DATE,
PRMNT_ACNTNG_TRNS.AMNT,
ACNTS.ACNT_SHRT_NAME,
PRMNT_ACNTNG_TRNS.CONTRA_ACNT,
PRMNT_ACNTNG_TRNS.DTLS,
PRMNT_ACNTNG_TRNS.DTLS2
 from PRMNT_ACNTNG_TRNS
 left join ACNTS on PRMNT_ACNTNG_TRNS.FIRM_CODE=ACNTS.FIRM_CODE and PRMNT_ACNTNG_TRNS.CONTRA_ACNT=ACNTS.ACNT_CODE
 left join CUSTS on ACNTS.FIRM_CODE=CUSTS.FIRM_CODE and ACNTS.acnt_code=CUSTS.acnt_code
 where PRMNT_ACNTNG_TRNS.FIRM_CODE=21
  and custs.cust_code= '1'--'03220174'
 AND ("PRMNT_ACNTNG_TRNS"."PRMY_TRNS_CLSS"=217 OR "PRMNT_ACNTNG_TRNS"."PRMY_TRNS_CLSS"=222) 
   and "PRMNT_ACNTNG_TRNS"."LINE_SIGN"=1
 ORDER BY "PRMNT_ACNTNG_TRNS"."FIRM_CODE", "PRMNT_ACNTNG_TRNS"."BLNC_YEAR", "PRMNT_ACNTNG_TRNS"."DOC_NBR"

 ;


-- orginal pamt_acnt query 
 SELECT "PRMNT_ACNTNG_TRNS"."FIRM_CODE", "PRMNT_ACNTNG_TRNS"."PRMY_TRNS_CLSS", "PRMNT_ACNTNG_TRNS"."ACNT_CODE", "PRMNT_ACNTNG_TRNS"."BLNC_YEAR", "PRMNT_ACNTNG_TRNS"."DOC_NBR", "PRMNT_ACNTNG_TRNS"."EVNT_DATE", "PRMNT_ACNTNG_TRNS"."AMNT", "PRMNT_ACNTNG_TRNS"."CONTRA_ACNT", "PRMNT_ACNTNG_TRNS"."DTLS", "PRMNT_ACNTNG_TRNS"."DTLS2", "ACNTS"."ACNT_SHRT_NAME", "PRMNT_ACNTNG_TRNS"."LINE_SIGN"
 FROM   "DBTRANS"."PRMNT_ACNTNG_TRNS" "PRMNT_ACNTNG_TRNS" INNER JOIN "DBTRANS"."ACNTS" "ACNTS" ON ("PRMNT_ACNTNG_TRNS"."FIRM_CODE"="ACNTS"."FIRM_CODE") AND ("PRMNT_ACNTNG_TRNS"."CONTRA_ACNT"="ACNTS"."ACNT_CODE")
 WHERE  "PRMNT_ACNTNG_TRNS"."ACNT_CODE"=1 
 AND "PRMNT_ACNTNG_TRNS"."FIRM_CODE"=40
 AND ("PRMNT_ACNTNG_TRNS"."PRMY_TRNS_CLSS"=217 OR "PRMNT_ACNTNG_TRNS"."PRMY_TRNS_CLSS"=222) 
 ORDER BY "PRMNT_ACNTNG_TRNS"."FIRM_CODE", "PRMNT_ACNTNG_TRNS"."BLNC_YEAR", "PRMNT_ACNTNG_TRNS"."DOC_NBR"



 --GUARANTIES
select * from GUARANTIES;

select
count(PRMNT_ACNTNG_TRNS.CONTRA_ACNT) as counter,
 PRMNT_ACNTNG_TRNS.firm_code,
acnts.acnt_code,
CUSTS.cust_code,
guaranties.evnt_date
from PRMNT_ACNTNG_TRNS
 left join ACNTS on PRMNT_ACNTNG_TRNS.FIRM_CODE=ACNTS.FIRM_CODE and PRMNT_ACNTNG_TRNS.CONTRA_ACNT=ACNTS.ACNT_CODE
 left join CUSTS on ACNTS.FIRM_CODE=CUSTS.FIRM_CODE and ACNTS.acnt_code=CUSTS.acnt_code
 left join guaranties on CUSTS.FIRM_CODE=guaranties.FIRM_CODE and CUSTS.CUST_CODE=guaranties.CUST_CODE
  where custs.cust_code is not null
  and guaranties.evnt_date is not null
 group by PRMNT_ACNTNG_TRNS.firm_code,acnts.acnt_code,CUSTS.cust_code
,guaranties.evnt_date
 order by counter;

select * from guaranties
where FIRM_CODE=18
and cust_code='123';