SELECT 
    "LGSTC_FRCST_TRNS"."LINE_NBR", 
    "LGSTC_FRCST_TRNS"."LINE_TRNS_STAT", 
    "LGSTC_FRCST_TRNS"."PART_PRC", 
    "LGSTC_FRCST_TRNS"."QNTY", 
    "LGSTC_FRCST_TRNS"."SHIP_QNTY", 
    "LGSTC_FRCST_TRNS"."AMNT_AFTR_RDCT", 
    "LGSTC_FRCST_TRNS"."FIRM_CODE", 
    "LGSTC_FRCST_TRNS"."PART_CODE", 
    "LGSTC_FRCST_TRNS"."PRMY_TRNS_CLSS", 
    "LGSTC_FRCST_TRNS"."DOC_NBR", 
    "LGSTC_FRCST_TRNS"."STRM_CODE", 
    "LGSTC_FRCST_TRNS"."RQSTD_SHIP_DATE", 
    "LGSTC_FRCST_TRNS"."PART_CODE", 
    "LGSTC_FRCST_TRNS"."UNIT_CODE", 
    -- "UNIT_NAMES"."UNIT_SHRT_NAME", 
    -- "PARTS"."PART_LONG_NAME", 
    get_part_dscr("LGSTC_FRCST_TRNS"."FIRM_CODE", "LGSTC_FRCST_TRNS"."PART_CODE", "LGSTC_FRCST_TRNS"."PRMY_TRNS_CLSS", "LGSTC_FRCST_TRNS"."DOC_NBR", "LGSTC_FRCST_TRNS"."LINE_NBR", 'XH', "LGSTC_FRCST_TRNS"."SPLR_CODE", "LGSTC_FRCST_TRNS"."PART_CODE") as PART_DSCR, 
    GET_PART_DSCR("LGSTC_FRCST_TRNS"."FIRM_CODE","LGSTC_FRCST_TRNS"."PART_CODE","LGSTC_FRCST_TRNS"."PRMY_TRNS_CLSS", "LGSTC_FRCST_TRNS"."DOC_NBR","LGSTC_FRCST_TRNS"."LINE_NBR",'XH','*','*') as PART_DSCR_XH, 
    GET_PART_DSCR("LGSTC_FRCST_TRNS"."FIRM_CODE","LGSTC_FRCST_TRNS"."PART_CODE","LGSTC_FRCST_TRNS"."PRMY_TRNS_CLSS", "LGSTC_FRCST_TRNS"."DOC_NBR","LGSTC_FRCST_TRNS"."LINE_NBR",'R',"LGSTC_FRCST_TRNS"."SPLR_CODE","LGSTC_FRCST_TRNS"."CUST_CODE") as PART_DSCR_R
    -- , 
    -- "VU_WEB_DOC_RMRKS"."RMRK" 
FROM 
    "LGSTC_FRCST_TRNS" 
-- LEFT JOIN  "UNIT_NAMES" ON "LGSTC_FRCST_TRNS"."UNIT_CODE" = "UNIT_NAMES"."UNIT_CODE" 
-- LEFT JOIN  "PARTS" ON ("LGSTC_FRCST_TRNS"."PART_CODE" = "PARTS"."PART_CODE" AND "PARTS"."FIRM_CODE" = 21) 
-- -- LEFT JOIN  "VU_WEB_DOC_RMRKS" ON ("LGSTC_FRCST_TRNS"."FIRM_CODE" = "VU_WEB_DOC_RMRKS"."FIRM_CODE" AND "LGSTC_FRCST_TRNS"."PRMY_TRNS_CLSS" = "VU_WEB_DOC_RMRKS"."PRMY_TRNS_CLSS" AND "LGSTC_FRCST_TRNS"."DOC_NBR" = "VU_WEB_DOC_RMRKS"."DOC_NBR" AND "LGSTC_FRCST_TRNS"."LINE_NBR" = "VU_WEB_DOC_RMRKS"."LINE_NBR") 
WHERE 
    "LGSTC_FRCST_TRNS"."FIRM_CODE" = 21 AND 
    "LGSTC_FRCST_TRNS"."DOC_NBR" = 15084 AND 
    "LGSTC_FRCST_TRNS"."PRMY_TRNS_CLSS" = 332 ;
    -- AND "LGSTC_FRCST_TRNS"."LINE_TRNS_STAT" < 50;

