module.exports=
    {
        "lgstc_frcst_doc": {
            "DOC_NBR": 1,
            "RDCT_PCNT": null,
            "AMNT_BFOR_RDCT": 331.3435,
            "AMNT_AFTR_RDCT": 331.63225,
            "EVNT_DATE": "1996-10-30T21:00:00.000Z",
            "PRMY_TRNS_CLSS": 342,
            "TRNS_STAT": 30,
            "PRFM_BY_NAME": "שרון",
            "FREE_FLD_1": null,
            "FIRM_CODE": 11,
            "DOC_STAT": "ס",
            "DOC_RMRK": "הזמנה רגילה",
            "SPLR_CODE": "123",
            "STRM_CODE": " .",
            "CUR_CODE": 1,
            "CREDIT_CODE": 11,
            "STRM_NAME": "מיקומים לא מוכתבים",
            "CREDIT_DSCR": "שוטף+30",
            "FORMAL_USER_NAME": null,
            "REP_EMP_NAME": "אביה",
            "ACTL_END_TIME": null,
            "CUR_SHRT_NAME": "ש\"ח",
            "PHON_AT_HOME": "0548965456",
            "FUN_ACTL_END_TIME": "טיוטה",
            "FUN_GET_VAT_COG": 17
        },
        "lgstc_frcst_trns": [
            {
                "LINE_NBR": 1,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 2,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 3,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 4,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 5,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 6,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 7,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 8,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 9,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 10,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 11,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 12,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 13,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 14,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 15,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 16,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 17,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 18,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 19,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 20,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 21,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 22,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 23,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 24,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 25,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 26,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 27,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 28,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 29,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 30,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 31,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 32,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 33,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 34,
                "PART_PRC": 5,
                "QNTY": 50,
                "AMNT_AFTR_RDCT": 252.45674,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "752",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1996-11-14T21:00:00.000Z",
                "PART_CODE_1": "752",
                "UNIT_CODE": 2,
                "UNIT_SHRT_NAME": "מ\"א",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "אינו מנהל מלאי",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "752",
                "FUN_GET_PART_DSCR_R": "זהירות, שביר! נא להעביר בזהירות מירבית. אין אחריות על פציעה"
            },
            {
                "LINE_NBR": 35,
                "PART_PRC": 2,
                "QNTY": 40,
                "AMNT_AFTR_RDCT": 83.349,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "754",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "1900-11-14T21:00:00.000Z",
                "PART_CODE_1": "754",
                "UNIT_CODE": 6,
                "UNIT_SHRT_NAME": "ק\"ג",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": "פריט בעל יחידה משנית...................\"",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "754",
                "FUN_GET_PART_DSCR_R": null
            },
            {
                "LINE_NBR": 36,
                "PART_PRC": 1,
                "QNTY": 1,
                "AMNT_AFTR_RDCT": 1.234,
                "LINE_TRNS_STAT": 30,
                "FIRM_CODE": 21,
                "PART_CODE": "755",
                "PRMY_TRNS_CLSS": 342,
                "DOC_NBR": 1,
                "STRM_CODE": " .",
                "RQSTD_SHIP_DATE": "2000-11-14T21:00:00.000Z",
                "PART_CODE_1": "755",
                "UNIT_CODE": 17,
                "UNIT_SHRT_NAME": "קופסה",
                "CAT_NBR_DSCR_1": null,
                "PART_LONG_NAME": " ERAN פריט אריזה ABC",
                "FUN_GET_PART_DSCR_X": null,
                "FUN_GET_PART_DSCR_PI": "755",
                "FUN_GET_PART_DSCR_R": null
            }
        ],
        "firm": {
            "CITY": "בני ברק",
            "FAX_AREA_CODE": "06",
            "FAX": "6321364",
            "AREA_PHON_CODE": "04",
            "PHON": "6321363",
            "POB_CODE": 12345,
            "ZIP_CODE": 30050,
            "BSNS_NBR": "557398252",
            "FIRM_LONG_NAME": "פיתוח 9 -Uni9D"
        },
        "splr": {
            "SPLR_LONG_DSCR": "ספק פטור ממע\"מ",
            "SPLR_CODE": "123",
            "CNTCT_PRSN": "Moran",
            "CITY_TO_SHIP": "עיר חלולה",
            "ZIP_TO_SHIP": 13524,
            "QTR_TO_SHIP": "דרך ללא מוצא 25",
            "STREET_TO_SHIP": "שולח לחמו על פני המים",
            "VAT_TYPE": "ח"
        }
    }
